const RECIPES = [
  // ── KAHVALTI ──────────────────────────────────────────────────────────────
  {
    id: "r1",
    title: "Menemen",
    emoji: "🍳",
    category: "Kahvaltı",
    difficulty: "Kolay",
    time: "15 dk",
    xp: 50,
    concept: "Kavurma",
    ingredients: ["2 yumurta", "1 domates", "1 yeşil biber", "1/2 soğan", "zeytinyağı", "tuz", "pul biber"],
    steps: [
      { action: "Zeytinyağını tavaya koy, orta ateşe al", tip: "Yağ çok ısınmasın — parmağını yaklaştırınca hafif sıcaklık hissetmelisin", concept: null },
      { action: "Soğanı ince ince doğra, yağda kavur", tip: "Saydam görünene kadar ~4-5 dk. Yanmasın, sadece yumuşasın", concept: "soğan kavurma" },
      { action: "Biberi ince doğra, soğana ekle, 2 dk kavur", tip: "Biber suyunu çekince hazır — hafif parlak görünür", concept: null },
      { action: "Domatesi küp küp doğra, ekle", tip: "Taze domates varsa suyunu sıkmadan ekle, suyu lezzet demek", concept: "domates suyu" },
      { action: "Tuz ve pul biber ekle, karıştır", tip: "Önce az tuz koy, piştikten sonra tadına bak, gerekirse ekle", concept: "tuz dengesi" },
      { action: "Yumurtaları kır, karıştırma!", tip: "Menemenin sırrı budur — az karıştırırsan kremsi olur, çok karıştırırsan lastik gibi", concept: null },
      { action: "Kapağı kapat, 2-3 dk bekle", tip: "Yumurtanın üstü beyazlaşınca hazır. Altı hâlâ biraz sıvı olabilir, bu normal", concept: null },
    ]
  },
  {
    id: "r2",
    title: "Sahanda Yumurta",
    emoji: "🍳",
    category: "Kahvaltı",
    difficulty: "Çok Kolay",
    time: "8 dk",
    xp: 30,
    concept: "Isı Kontrolü",
    ingredients: ["2 yumurta", "1 tatlı kaşığı tereyağı", "tuz", "karabiber"],
    steps: [
      { action: "Tavayı kısık ateşe koy, tereyağını ekle", tip: "Kısık ateş şart — yüksek ateşte yumurta tabanı yanar, üstü çiğ kalır", concept: "ısı kontrolü" },
      { action: "Tereyağı eriyince yumurtaları kır", tip: "Yumurtayı önce küçük bir kaseye kır, sonra tavaya aktar — sarı bütün kalsın", concept: null },
      { action: "Tuz ve karabiber serp", tip: "Sadece beyaza tuz serpebilirsin, sarıya değil — sarı pişince acılaşabilir", concept: null },
      { action: "Kapaksız 3-4 dk pişir, dokunma", tip: "Beyaz tamamen pişince, sarı hâlâ akışkan — işte o an çıkar. Fazla pişirme!", concept: null },
    ]
  },
  {
    id: "r3",
    title: "Omlet",
    emoji: "🥚",
    category: "Kahvaltı",
    difficulty: "Kolay",
    time: "10 dk",
    xp: 40,
    concept: "Çırpma & Katlama",
    ingredients: ["3 yumurta", "2 yemek kaşığı süt", "tuz", "tereyağı", "isteğe bağlı: kaşar, domates"],
    steps: [
      { action: "Yumurtaları kase içine kır, süt ve tuz ekle", tip: "Süt omleti yumuşatır, su değil süt kullan", concept: null },
      { action: "Çatal ya da çırpıcıyla iyice çırp", tip: "Sarı ve beyaz tamamen karışana kadar — en az 30 saniye çırp", concept: "çırpma" },
      { action: "Tavaya tereyağı koy, orta ateşte eritec", tip: "Tereyağı köpürmeye başlayınca yumurtayı dök", concept: null },
      { action: "Yumurtayı dök, kenarlara spatula ile itiyerek pişir", tip: "Kenarlardaki pişmiş kısmı ortaya katla — bu omletin sırrı", concept: "katlama" },
      { action: "İç malzemeyi ortaya koy (kaşar, domates vs)", tip: "Yumurta henüz biraz akışkanlıkla doldurmayı yap", concept: null },
      { action: "İkiye katla, 30 sn daha pişir, tabağa al", tip: "Üzeri altın rengi olunca hazır. Fazla bekleme — kurur", concept: null },
    ]
  },
  {
    id: "r4",
    title: "Kaşarlı Tost",
    emoji: "🥪",
    category: "Kahvaltı",
    difficulty: "Çok Kolay",
    time: "7 dk",
    xp: 25,
    concept: "Kızartma",
    ingredients: ["2 dilim ekmek", "2-3 dilim kaşar peyniri", "tereyağı"],
    steps: [
      { action: "Ekmeğin dış yüzlerine tereyağı sür", tip: "Dışı tereyağlı olursa altın rengi ve çıtır olur — içine değil dışına sür", concept: "kızartma" },
      { action: "Tavayı orta ateşe al", tip: "Tost makinesi yoksa tava mükemmel çalışır", concept: null },
      { action: "Ekmeği tavaya koy, üstüne kaşarı diz", tip: "Kaşarı bol koy — eriyince azalır", concept: null },
      { action: "Diğer dilimi üstüne kapat, spatulayla bastır", tip: "Hafifçe bastırmak peynirin erimesini hızlandırır", concept: null },
      { action: "Alt yüzü altın rengi olunca çevir (2-3 dk)", tip: "Sabırlı ol — erken çevirme, yanmadan güzel kızarsın", concept: null },
      { action: "Diğer yüzü de 2 dk pişir, çıkar", tip: "Peynir akıyorsa hazır demektir", concept: null },
    ]
  },

  // ── ÖĞLE ──────────────────────────────────────────────────────────────────
  {
    id: "r5",
    title: "Mercimek Çorbası",
    emoji: "🍲",
    category: "Öğle",
    difficulty: "Kolay",
    time: "25 dk",
    xp: 70,
    concept: "Çorba Temeli",
    ingredients: ["1 su bardağı kırmızı mercimek", "1 soğan", "1 havuç", "2 yemek kaşığı tereyağı", "tuz", "kimyon", "pul biber"],
    steps: [
      { action: "Soğan ve havucu küp küp doğra", tip: "Eşit boyut önemli — eşit pişerler", concept: null },
      { action: "Tereyağını tencereye koy, soğanı kavur", tip: "Altın rengi alana kadar ~5 dk, sürekli karıştır", concept: "kavurma" },
      { action: "Havucu ekle, 2 dk daha kavur", tip: "Havuç tatlılık katar çorbaya", concept: null },
      { action: "Mercimeği ekle, 3 bardak su dök", tip: "Kırmızı mercimeği yıkamak gerekmez, direkt ekle", concept: null },
      { action: "Kaynatıp kısık ateşte 20 dk pişir", tip: "Mercimek ezilene kadar bekle — kaşıkla bastırınca dağılıyorsa hazır", concept: null },
      { action: "Ocağı kapat, blenderdan geçir", tip: "Sıcakken dikkat! Blender kapağını bir bezle tut", concept: "blenderlama" },
      { action: "Ayrı tavada tereyağı eritip pul biber ekle, çorbanın üstüne dök", tip: "Bu adım çorbayı 10 kat güzel yapar, atlatma!", concept: "terbiye" },
    ]
  },
  {
    id: "r6",
    title: "Domates Çorbası",
    emoji: "🍅",
    category: "Öğle",
    difficulty: "Kolay",
    time: "20 dk",
    xp: 60,
    concept: "Asit Dengesi",
    ingredients: ["4 olgun domates", "1 soğan", "2 diş sarımsak", "1 yemek kaşığı tereyağı", "tuz", "şeker", "fesleğen"],
    steps: [
      { action: "Domatesleri soyup küp doğra", tip: "Kabuğu çıkarmak için üstüne çarpı çiz, kaynar suya 30 sn daldır — kabuk kendi gelir", concept: null },
      { action: "Soğan ve sarımsağı tereyağında kavur", tip: "Sarımsak yanmasın — soğan yumuşayınca ekle", concept: "kavurma" },
      { action: "Domatesleri ekle, tuz ve şeker koy", tip: "Şeker asitliği dengeler — sadece 1 tutam yeterli", concept: "asit dengesi" },
      { action: "Kısık ateşte 15 dk pişir", tip: "Domates suyu çekip koyulaşınca hazır", concept: null },
      { action: "Blenderdan geçir, süzgeçten geçirebilirsin", tip: "Süzgeçten geçirince ipeksi olur ama şart değil", concept: null },
      { action: "Fesleğen ekle, servis et", tip: "Taze fesleğen varsa pişirme — sadece üstüne koy", concept: null },
    ]
  },
  {
    id: "r7",
    title: "Tavuk Sote",
    emoji: "🍗",
    category: "Öğle",
    difficulty: "Orta",
    time: "25 dk",
    xp: 80,
    concept: "Et Mühürleme",
    ingredients: ["2 tavuk göğsü", "1 biber", "1 domates", "1 soğan", "zeytinyağı", "tuz", "karabiber", "kekik"],
    steps: [
      { action: "Tavuğu küp küp doğra", tip: "Eşit boyut şart — büyük parçalar çiğ, küçükler kurur", concept: null },
      { action: "Tavayı yüksek ateşe al, yağ ekle", tip: "Yüksek ateş tavuğu mühürler, suyu içinde kalır", concept: "et mühürleme" },
      { action: "Tavuğu ekle, karıştırma — 2 dk bekle", tip: "Karıştırırsan su çıkar, kavurmaz. Sabırlı ol!", concept: null },
      { action: "Tavuğu çevir, diğer yüzü de 2 dk pişir", tip: "Altın rengi görünce çevir — bu renk lezzet demek", concept: null },
      { action: "Soğan ve biberi ekle, karıştır", tip: "Ateşi kıs, sebzeler yumuşasın", concept: null },
      { action: "Domatesi ekle, tuz, karabiber, kekik ekle", tip: "Kekik tavukla çok iyi gider, cömert ol", concept: null },
      { action: "Kısık ateşte 10 dk pişir", tip: "Domates suyu çekilince hazır", concept: null },
    ]
  },
  {
    id: "r8",
    title: "Domates Soslu Makarna",
    emoji: "🍝",
    category: "Öğle",
    difficulty: "Kolay",
    time: "20 dk",
    xp: 55,
    concept: "Makarna Pişirme",
    ingredients: ["200g makarna", "2 domates ya da domates salçası", "3 diş sarımsak", "zeytinyağı", "tuz", "şeker", "fesleğen"],
    steps: [
      { action: "Büyük tencereye bol su koy, kaynat", tip: "Su az olursa makarna birbirine yapışır. Bol su şart", concept: null },
      { action: "Su kaynayınca tuz at, makarnayı ekle", tip: "Su tuzlu olmalı — deniz gibi. Bu makarnaya lezzet katar", concept: "makarna pişirme" },
      { action: "Pakette yazan süre kadar pişir, arada karıştır", tip: "1-2 dk erken çıkar, 'al dente' olsun — hafif direnç kalsın", concept: "al dente" },
      { action: "Ayrı tavada sarımsağı zeytinyağında kavur", tip: "Sarımsak altın rengi olunca çıkar — yanmasın, acılaşır", concept: null },
      { action: "Domatesi ekle, tuz ve şeker koy, 10 dk pişir", tip: "Sos koyulaşınca hazır — tahta kaşıkla geçince iz kalıyorsa tamam", concept: null },
      { action: "Makarnayı süz, sosa ekle, karıştır", tip: "Makarna suyundan 1 kase sakla — sosu açmak için kullanılabilir", concept: null },
      { action: "Fesleğen ekle, servis et", tip: "Rendelenmiş parmesan varsa üstüne — muhteşem olur", concept: null },
    ]
  },
  {
    id: "r9",
    title: "Pilav",
    emoji: "🍚",
    category: "Öğle",
    difficulty: "Orta",
    time: "30 dk",
    xp: 75,
    concept: "Su Oranı",
    ingredients: ["1 su bardağı pirinç", "1.5 su bardağı su", "1 yemek kaşığı tereyağı", "tuz"],
    steps: [
      { action: "Pirinci yıka, 10 dk suda beklet", tip: "Yıkamak nişastayı alır — pirinçler birbirine yapışmaz", concept: null },
      { action: "Tereyağını tencerede eritip pirinci ekle", tip: "1-2 dk kavur — pirincler şeffaflaşınca hazır", concept: "kavurma" },
      { action: "Sıcak suyu ekle, tuz at", tip: "Su oranı 1 bardak pirinç = 1.5 bardak su. Bu oran altın kural", concept: "su oranı" },
      { action: "Kaynatıp en kısık ateşe al, kapağı kapat", tip: "Kapağı sakın açma! Buhar kaçarsa pirinç pişmez", concept: null },
      { action: "18 dk bekle, ocağı kapat", tip: "Su tamamen çekilince hazır. Kapağı o zaman aç", concept: null },
      { action: "Üstüne temiz bez koy, kapağı kapat, 5 dk dinlendir", tip: "Bez fazla buharı emer — pilav tane tane olur", concept: "dinlendirme" },
    ]
  },

  // ── AKŞAM ─────────────────────────────────────────────────────────────────
  {
    id: "r10",
    title: "Fırında Tavuk Göğsü",
    emoji: "🍗",
    category: "Akşam",
    difficulty: "Kolay",
    time: "35 dk",
    xp: 85,
    concept: "Marinasyon",
    ingredients: ["2 tavuk göğsü", "zeytinyağı", "sarımsak tozu", "kekik", "paprika", "tuz", "karabiber"],
    steps: [
      { action: "Fırını 200 dereceye ısıt", tip: "Fırın önceden ısınmalı — soğuk fırına konan tavuk iyi pişmez", concept: null },
      { action: "Tavuğu zeytinyağı ve baharatlarla ovuştur", tip: "Her yeri kaplamasına dikkat et — bu marinasyon lezzeti içine işler", concept: "marinasyon" },
      { action: "Fırın kabına koy, üstünü folyo ile kapat", tip: "Folyo ilk 20 dk nem tutar, tavuk kurumaz", concept: null },
      { action: "20 dk pişir, folyoyu çıkar", tip: "Folyo olmadan son 15 dk — üstü güzel kızarır", concept: null },
      { action: "15 dk daha pişir", tip: "Bıçakla ortasını deli — pembe değil beyaz görünüyorsa hazır", concept: null },
      { action: "Fırından çıkar, 5 dk dinlendir", tip: "Hemen kesme — dinlendirince sular içinde kalır, sulu olur", concept: "dinlendirme" },
    ]
  },
  {
    id: "r11",
    title: "Köfte",
    emoji: "🥩",
    category: "Akşam",
    difficulty: "Orta",
    time: "30 dk",
    xp: 90,
    concept: "Et Yoğurma",
    ingredients: ["400g kıyma", "1 soğan", "2 diş sarımsak", "1 yumurta", "galeta unu", "tuz", "karabiber", "kimyon", "kekik"],
    steps: [
      { action: "Soğanı rendele, suyunu sık", tip: "Soğan suyu köfteyi dağıtır — iyice sıkman şart", concept: null },
      { action: "Tüm malzemeleri kaseye koy", tip: "Galeta unu bağlayıcı — olmadan köfte dağılır", concept: null },
      { action: "En az 5 dk yoğur", tip: "Ne kadar çok yoğurursan o kadar lezzetli — eller en iyi araç", concept: "et yoğurma" },
      { action: "Buzdolabında 30 dk dinlendir", tip: "Bu adım köftenin şeklini tutmasını sağlar, atlatma", concept: "dinlendirme" },
      { action: "Ceviz büyüklüğünde kopar, şekillendir", tip: "Ellerini ıslatırsan yapışmaz", concept: null },
      { action: "Kızgın tavada her yüzü 3-4 dk pişir", tip: "Tava çok sıcak olmalı — öyle güzel iz bırakır", concept: null },
    ]
  },
  {
    id: "r12",
    title: "Sebzeli Güveç",
    emoji: "🥘",
    category: "Akşam",
    difficulty: "Kolay",
    time: "45 dk",
    xp: 80,
    concept: "Yavaş Pişirme",
    ingredients: ["2 patates", "2 havuç", "1 kabak", "1 biber", "1 soğan", "2 domates", "zeytinyağı", "tuz", "kekik"],
    steps: [
      { action: "Tüm sebzeleri büyük küpler doğra", tip: "Büyük doğra — uzun pişeceği için küçük doğrarsan dağılır", concept: null },
      { action: "Fırını 180 dereceye ısıt", tip: "Güveç düşük ısıda uzun pişer — acele etme", concept: "yavaş pişirme" },
      { action: "Güveç kabına soğanı, havucu, patatesi diz", tip: "Sert sebzeler alta — daha uzun pişmeleri lazım", concept: null },
      { action: "Kabak ve biberi üstüne ekle", tip: "Yumuşak sebzeler üste gider", concept: null },
      { action: "Domatesi en üste koy, zeytinyağı ve tuz gezdir", tip: "Domates suyu alta sızar, her şeyi pişirir", concept: null },
      { action: "Üstünü kapakla ya da folyoyla kapat, 40 dk pişir", tip: "Aç bakmak yasak! Buhar kaçmasın", concept: null },
      { action: "Kekik serp, 5 dk daha pişir", tip: "Kekiği erken koymak aromasını uçurur — son anda ekle", concept: null },
    ]
  },
  {
    id: "r13",
    title: "Kıymalı Biber Dolması",
    emoji: "🫑",
    category: "Akşam",
    difficulty: "Orta",
    time: "50 dk",
    xp: 100,
    concept: "Dolma Tekniği",
    ingredients: ["6 dolmalık biber", "300g kıyma", "1 su bardağı pirinç", "1 soğan", "salça", "tuz", "karabiber", "nane"],
    steps: [
      { action: "Biberlerin tepesini kes, içini temizle", tip: "Tohumları çıkar ama tamamen delmemeye dikkat et", concept: null },
      { action: "Soğanı rendele, kıymayla karıştır", tip: "Soğan suyunu sıkmadan ekle — iç harcı nemli olsun", concept: null },
      { action: "Pirinci, tuz, karabiber, nane ekle, yoğur", tip: "Pirinç çiğ giriyor — pişince şişeceği için az dolduracaksın", concept: "dolma tekniği" },
      { action: "Biberleri 3/4'üne kadar doldur", tip: "Fazla doldurma — pirinç şişer, biber çatlar", concept: null },
      { action: "Biberleri tencereye dik olarak diz", tip: "Birbirine yaslanarak dursunlar, devrilmesin", concept: null },
      { action: "Salçayla karışık su ekle (biberlerin yarısına kadar)", tip: "Salçalı su hem pişirir hem lezzet katar", concept: null },
      { action: "Kısık ateşte kapakla 35-40 dk pişir", tip: "Pirinç pişince hazır — bir tanesini aç kontrol et", concept: null },
    ]
  },
  {
    id: "r14",
    title: "Fırın Patates",
    emoji: "🥔",
    category: "Akşam",
    difficulty: "Çok Kolay",
    time: "40 dk",
    xp: 45,
    concept: "Fırın Teknikleri",
    ingredients: ["4 orta boy patates", "zeytinyağı", "tuz", "karabiber", "sarımsak tozu", "kekik", "paprika"],
    steps: [
      { action: "Fırını 200 dereceye ısıt", tip: "Yüksek ısı patatesin dışını çıtır yapar", concept: "fırın teknikleri" },
      { action: "Patatesleri soy, dilim ya da küp doğra", tip: "Eşit kalınlık şart — ince olanlar yanar, kalın olanlar çiğ kalır", concept: null },
      { action: "Kurulamak için kağıt havluyla pat pat sil", tip: "Kuru patates daha çıtır olur — nemli patates buharda pişer", concept: null },
      { action: "Zeytinyağı ve baharatları ekle, karıştır", tip: "Her parça yağlansın — yağsız olan parçalar kurur", concept: null },
      { action: "Tek kat halinde fırın tepsisine diz", tip: "Üst üste koyma! Üst üste olursa çıtır değil yumuşak olur", concept: null },
      { action: "30-35 dk pişir, yarıda bir çevir", tip: "Altın rengi ve çıtır görününce hazır", concept: null },
    ]
  },

  // ── ARA ───────────────────────────────────────────────────────────────────
  {
    id: "r15",
    title: "Cacık",
    emoji: "🥒",
    category: "Ara",
    difficulty: "Çok Kolay",
    time: "10 dk",
    xp: 30,
    concept: "Soğuk Sos",
    ingredients: ["2 su bardağı yoğurt", "1 salatalık", "2 diş sarımsak", "zeytinyağı", "tuz", "nane", "dereotu"],
    steps: [
      { action: "Salatalığı rendele ya da küçük küp doğra", tip: "Rendele şecenin suyunu süzmesi daha kolay olur", concept: null },
      { action: "Salatalığın suyunu sık", tip: "Su cacığı sulu yapar — iyice sık", concept: null },
      { action: "Sarımsağı ezdire ezdire tuz ile ez", tip: "Tuzla ezmek sarımsağı pasta haline getirir — cacığa düzgün dağılır", concept: "soğuk sos" },
      { action: "Yoğurt, salatalık, sarımsak, nane, dereotu karıştır", tip: "Yoğurt tam yağlı olursa çok daha lezzetli", concept: null },
      { action: "Üstüne zeytinyağı gezdir, servis et", tip: "Soğuk servis et — buzdolabında 1 saat beklerse daha güzel olur", concept: null },
    ]
  },
  {
    id: "r16",
    title: "Haşlanmış Yumurta",
    emoji: "🥚",
    category: "Ara",
    difficulty: "Çok Kolay",
    time: "12 dk",
    xp: 20,
    concept: "Haşlama Süresi",
    ingredients: ["4 yumurta", "su", "tuz"],
    steps: [
      { action: "Yumurtaları buzdolabından çıkar, oda sıcaklığına gelsin", tip: "Soğuk yumurta sıcak suya girince çatlayabilir", concept: null },
      { action: "Tencereye su koy, kaynat", tip: "Su yumurtaları örtecek kadar çok olsun", concept: null },
      { action: "Kaşıkla yavaşça suya indir", tip: "Fırlatma — nazikçe bırak", concept: "haşlama süresi" },
      { action: "Rafadan için 6 dk, katı için 10 dk bekle", tip: "6 dk = sarı akışkan. 8 dk = sarı yarı katı. 10 dk = tamamen katı", concept: null },
      { action: "Soğuk suya al, 2 dk beklet", tip: "Soğuk su pişmeyi durdurur ve kabuğun kolayca soyulmasını sağlar", concept: null },
      { action: "Kabuğu soy, tuzla ye", tip: "Kabuğu çatlatıp su altında soyarsan daha kolay çıkar", concept: null },
    ]
  },
  {
    id: "r17",
    title: "Humus",
    emoji: "🫘",
    category: "Ara",
    difficulty: "Kolay",
    time: "10 dk",
    xp: 40,
    concept: "Blenderlama",
    ingredients: ["400g konserve nohut", "3 yemek kaşığı tahin", "1 limon suyu", "2 diş sarımsak", "zeytinyağı", "tuz", "kimyon", "paprika"],
    steps: [
      { action: "Nohutu süz, bir miktar suyunu sakla", tip: "Nohut suyu (aquafaba) humusun kıvamını ayarlamak için kullanılır", concept: null },
      { action: "Sarımsak ve limon suyunu blendere koy, çek", tip: "Sarımsağı önce çekmek acılığını azaltır", concept: null },
      { action: "Tahin ekle, 1 dk çek", tip: "Tahin humusun kremsi yapısını sağlar — cömert ol", concept: "blenderlama" },
      { action: "Nohutu ekle, yüksek hızda 3-4 dk çek", tip: "Ne kadar uzun çekersen o kadar kremsi olur — sabır!", concept: null },
      { action: "Kıvam için nohut suyu ekle, tuz ayarla", tip: "Az az ekle — çok sıvı olmasın", concept: null },
      { action: "Tabağa al, zeytinyağı, paprika ve kimyon serp", tip: "Servis önemli — güzel sunulan humus daha lezzetli görünür", concept: null },
    ]
  },
];

export default RECIPES;
